spring:
  application:
    name: aws-lambda-spring-cloud
  main:
    web-application-type: none   # ← ADD THIS
  cloud:
    function:
      definition: functionRouter
      routing-expression: headers['function.name']
